server:
  port: 9000

spring:
  application:
    name: spring-boot-api

logging:
  level:
    org.mybatis: DEBUG
    org.apache.ibatis: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

allowed-domains:
  domains:
    - localhost:9000
    - 127.0.0.1:9000

allowed-endpoints:
  endpoints:
    - /api-docs/**
    - /swagger-ui/**
    - /auth/accessToken
    - /user/signIn

jwt:
  secretKey: spring-boot-api-dfkglndsflgknsdlkgnerlkgnerlkgnerlk


