server:
  port: 9000

spring:
  application:
    name: spring-boot-api
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/swagger_test
    username: postgres
    password: 1234
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org:
      springframework:
        security: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

allowed-domains:
  domains:
    - localhost:9000
    - 127.0.0.1:9000

jwt:
  secretKey: spring-boot-api-dfkglndsflgknsdlkgnerlkgnerlkgnerlk


