server:
  port: 9000

spring:
  application:
    name: spring-boot-api
  messages:
    encoding: UTF-8
    basename: messages/error
  profiles:
    include: secret

logging:
  level:
    org.mybatis: DEBUG
    org.apache.ibatis: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

allowed-domains:
  domains:
    - localhost:9000
    - 127.0.0.1:9000

allowed-endpoints:
  endpoints:
    - /api-docs/**
    - /swagger-ui/**
    - /auth/**
    - /user/sign-in
    - /user/sign-up

jwt:
  secretKey: spring-boot-api-dfkglndsflgknsdlkgnerlkgnerlkgnerlk

front:
  login:
    redirection-uri: http://localhost:3000

auth:
  login:
    naver:
      authorization-uri: https://nid.naver.com/oauth2.0/authorize?response_type=code&client_id=%s&redirect_uri=%s&state=%s
      redirection-uri: http://localhost:9000/auth/naver/callback
      access-token-uri: https://nid.naver.com/oauth2.0/token?grant_type=authorization_code&client_id=%s&client_secret=%s&code=%s&state=%s
      member-profile-uri: https://openapi.naver.com/v1/nid/me
    google:
      authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?scope=openid%%20email%%20profile&response_type=code&client_id=%s&redirect_uri=%s&state=%s
      redirection-uri: http://localhost:9000/auth/google/callback
      access-token-uri: https://oauth2.googleapis.com/token
      member-profile-uri: https://www.googleapis.com/oauth2/v3/userinfo


